export const GET_LISTING = 'GET_LISTING'
export const GET_LISTING_SUCCESS = 'GET_LISTING_SUCCESS'
export const GET_LISTING_FAILED = 'GET_LISTING_FAILED'

export const GET_DETAIL_ITEM = 'GET_DETAIL_ITEM'
export const GET_DETAIL_ITEM_SUCCESS = 'GET_DETAIL_ITEM_SUCCESS'
export const GET_DETAIL_ITEM_FAILED = 'GET_DETAIL_ITEM_FAILED'